// <auto-generated />
using ContcatXamarin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContcatXamarin.Migrations
{
    [DbContext(typeof(Repository))]
    [Migration("20200305102915_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("ContcatXamarin.Models.User", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("REAL");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1.0,
                            Address = "CCC",
                            LastName = "BBB",
                            Name = "AAA",
                            Number = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
